# Build film54.html: the 54-second "Know. Watch. Decide." film.
# Engine pieces (helpers, source tiles, background, camera) are taken from film.html; the scenes live in film54_src/.
import re
src=open('film.html',encoding='utf-8').read()
def between(a,b):
    i=src.index(a); j=src.index(b,i); return src[i:j]
def fn(name):
    i=src.index(f'function {name}('); j=src.index('{',i); d=0
    for k in range(j,len(src)):
        d+= src[k]=='{'; d-= src[k]=='}'
        if d==0: return src[i:k+1]
fonts='\n'.join(l for l in src.splitlines() if l.startswith('@font-face'))
helpers=between('/* ================= helpers ================= */','/* ================= build static structures ================= */')
brands=re.search(r'^const BRANDS=.*$',src,re.M).group(0)
tiles=re.search(r'const TILES=\[.*?\];',src,re.S).group(0)
canv=between('/* ================= canvases ================= */','/* ================= TRANSITIONS')
cam=re.search(r'^let CAM=.*$',src,re.M).group(0)+'\n'+fn('camState')+'\n'+fn('camera')
css=open('film54_src/style.css',encoding='utf-8').read()
body=open('film54_src/body.html',encoding='utf-8').read()
scenes=open('film54_src/scenes.js',encoding='utf-8').read()
html=f'''<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>MARSAD — Know. Watch. Decide. (54s)</title>
<link rel="stylesheet" href="site_kit.css">
<style>
{fonts}
{css}
</style>
<script src="site_kit.js"></script>
</head>
<body>
{body}
<script>
/* generated by make_film54.py — edit film54_src/ and rebuild */
{helpers}
/* ================= source tiles (shared with film.html) ================= */
{brands}
{tiles}
{fn('tileHTML')}

{canv}
/* ================= camera (shared with film.html) ================= */
{cam}

{scenes}
</script>
</body>
</html>
'''
open('film54.html','w',encoding='utf-8').write(html); print('film54.html',len(html))
