"""Write the Monitor film's renderable pages: films/monitor/ -> build/monitor-<cut>.html

usage: python3 films/monitor/make.py [cut ...]        default: every cut in CUTS
       python3 films/monitor/make.py --list           print the cut names

A cut is a format (9x16, 16x9, 1x1), a language (ar, en), an end card (organic, paid) and a kind (hero 13 s,
bumper 6 s). The page gets window.CUT and window.DATA (data.json) and runs monitor.js.
"""
import json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))

CUTS = {
    'hero-9x16':        dict(fmt='9x16', lang='ar', end='organic', kind='hero'),
    'hero-9x16-paid':   dict(fmt='9x16', lang='ar', end='paid', kind='hero'),
    'hero-9x16-en':     dict(fmt='9x16', lang='en', end='organic', kind='hero'),
    'hero-16x9':        dict(fmt='16x9', lang='ar', end='organic', kind='hero'),
    'hero-16x9-en':     dict(fmt='16x9', lang='en', end='organic', kind='hero'),
    'hero-1x1':         dict(fmt='1x1', lang='ar', end='organic', kind='hero'),
    'hero-1x1-en':      dict(fmt='1x1', lang='en', end='organic', kind='hero'),
    'bumper-9x16':      dict(fmt='9x16', lang='ar', end='organic', kind='bumper'),
    'bumper-16x9':      dict(fmt='16x9', lang='ar', end='organic', kind='bumper'),
}


def page(name, cut, data):
    return f'''<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<base href="../">
<title>Marsad Monitor Film — {name}</title>
<link rel="stylesheet" href="films/monitor/monitor.css">
</head>
<body>
<!-- generated by films/monitor/make.py — edit films/monitor/, then rebuild -->
<div id="stage"></div>
<script>window.CUT={json.dumps(cut)};window.DATA={json.dumps(data, ensure_ascii=False)};</script>
<script src="films/monitor/monitor.js"></script>
</body>
</html>
'''


def main():
    if '--list' in sys.argv:
        print(' '.join(CUTS))
        return
    names = [a for a in sys.argv[1:] if not a.startswith('-')] or list(CUTS)
    bad = [n for n in names if n not in CUTS]
    if bad:
        sys.exit(f'unknown cut(s) {bad}; use {list(CUTS)}')
    with open(os.path.join(HERE, 'data.json'), encoding='utf-8') as f:
        data = json.load(f)
    os.makedirs(os.path.join(ROOT, 'build'), exist_ok=True)
    for n in names:
        out = os.path.join(ROOT, 'build', f'monitor-{n}.html')
        with open(out, 'w', encoding='utf-8') as f:
            f.write(page(n, CUTS[n], data))
        print('wrote', os.path.relpath(out, ROOT))


if __name__ == '__main__':
    main()
