"""Assemble a demo into renderable pages: demos/<slug>/ -> build/<slug>-16x9.html and build/<slug>-9x16.html.

usage: python3 tools/make_demo.py <slug>              write the pages
       python3 tools/make_demo.py <slug> --formats    print the formats listed in demo.json (used by build_demo.sh)

A demo folder holds:
  demo.json   title, duration (s), formats, music {file, bpm, downbeat, start, loop, fade_in, fade_out}
  demo.js     the timeline, written against the engine API (engine/engine.js); ends with M.start()
  demo.css    optional extra styles        pages.js  optional custom pages (M.definePage)
The page gets window.DEMO = {slug, title, format, duration, bpm, phase}; phase is the video time of the first
downbeat, so M.B(0) is a downbeat and M.B(4k) are bar lines.
"""
import json, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FORMATS = ('16x9', '9x16')


def load(slug):
    d = os.path.join(ROOT, 'demos', slug)
    if not os.path.isdir(d):
        sys.exit(f'no demo folder: demos/{slug}')
    with open(os.path.join(d, 'demo.json'), encoding='utf-8') as f:
        meta = json.load(f)
    if not os.path.isfile(os.path.join(d, 'demo.js')):
        sys.exit(f'demos/{slug}/demo.js is missing')
    fmts = meta.get('formats', list(FORMATS))
    bad = [f for f in fmts if f not in FORMATS]
    if bad:
        sys.exit(f'unknown format(s) {bad}; use {FORMATS}')
    return d, meta, fmts


def grid(meta):
    """bpm and the video time of the first downbeat (both None without music)."""
    m = meta.get('music') or {}
    if not m.get('bpm'):
        return None, 0.0
    bpm = float(m['bpm'])
    bar = 4 * 60.0 / bpm
    phase = (float(m.get('downbeat', 0.0)) - float(m.get('start', 0.0))) % bar
    return bpm, round(phase, 5)


def page(slug, d, meta, fmt):
    bpm, phase = grid(meta)
    demo = {'slug': slug, 'title': meta.get('title', slug), 'format': fmt,
            'duration': float(meta['duration']), 'bpm': bpm, 'phase': phase}
    extra_css = f'<link rel="stylesheet" href="demos/{slug}/demo.css">\n' if os.path.isfile(os.path.join(d, 'demo.css')) else ''
    pages_js = f'<script src="demos/{slug}/pages.js"></script>\n' if os.path.isfile(os.path.join(d, 'pages.js')) else ''
    return f'''<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<base href="../">
<title>{demo['title']} — {fmt}</title>
<link rel="stylesheet" href="site_kit.css">
<link rel="stylesheet" href="engine/engine.css">
{extra_css}</head>
<body>
<!-- generated by tools/make_demo.py from demos/{slug}/ — edit the demo folder, then rebuild -->
<script>window.DEMO={json.dumps(demo, ensure_ascii=False)};</script>
<script src="site_kit.js"></script>
<script src="engine/engine.js"></script>
{pages_js}<script src="demos/{slug}/demo.js"></script>
</body>
</html>
'''


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    slug = sys.argv[1]
    d, meta, fmts = load(slug)
    if '--formats' in sys.argv:
        print(' '.join(fmts))
        return
    os.makedirs(os.path.join(ROOT, 'build'), exist_ok=True)
    for fmt in fmts:
        out = os.path.join(ROOT, 'build', f'{slug}-{fmt}.html')
        with open(out, 'w', encoding='utf-8') as f:
            f.write(page(slug, d, meta, fmt))
        print('wrote', os.path.relpath(out, ROOT))


if __name__ == '__main__':
    main()
